name: jokes_app
description: A new Flutter project about Jokes that are fetched through api.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  sqflite: ^1.3.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
         - asset: fonts/Roboto/Roboto-Medium.ttf
